services:
  db:
    container_name: postgres_container2
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quiz
    ports:
      - "5432:5432"
    volumes: 
  
  adminer:
    image: adminer
    ports:
      - "8080:8080"