services:
  db:
    container_name: postgres_container1
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quiz
    ports:
      - "5432:5432"
    volumes: 
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql  
      - ./db/insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql
     
  adminer:
    image: adminer
    ports:
      - "8080:8080"


